language: python

python:
  - "2.6"
  - "2.7"

os:
  - linux


sudo: false

install:
  - "pip install 'argparse>=1.2.1' --allow-all-external"
  - pip install boto certauth
  - python setup.py -q install
  - pip install coverage pytest-cov coveralls --use-mirrors
  - npm install

script:
  - python setup.py test
  - cd karma-tests && make test

after_success:
    coveralls
