# pywb config file
# ========================================
#

collections:
    pywb:
        index: ./sample_archive/cdx/
        resource: ./sample_archive/warcs/

# Settings for each collection
use_js_obj_proxy: true

# Memento support, enable
enable_memento: true

# Replay content in an iframe
framed_replay: true

