#collections:
#    pywb: ./sample_archive/cdx/

#archive_paths: ./sample_archive/warcs/

collections_root: collections

paths:
    archive_paths: warcs
    index_paths: cdx
    static_path: static

    templates_dir: templates

    template_files:
        banner_html: banner.html
        head_insert_html: head_insert.html
        frame_insert_html: frame_insert.html

        query_html: query.html
        search_html: search.html
        not_found_html: not_found.html

    shared_template_files:
        home_html: index.html
        error_html: error.html

        proxy_cert_download_html: proxy_cert_download.html
        proxy_select_html: proxy_select.html

head_insert_html: ui/head_insert.html
frame_insert_html: ui/frame_insert.html
banner_html: banner.html

home_html: ui/index.html

query_html: ui/query.html
search_html: ui/search.html

error_html: ui/error.html
not_found_html: ui/not_found.html

proxy_cert_download_html: ui/proxy_cert_download.html
proxy_select_html: ui/proxy_select.html

template_globals:
    static_path: static/default

static_routes:
    static/default: pywb/static/

enable_memento: true

domain_specific_rules: pywb/rules.yaml

framed_replay: true
